services:
  api:
    build: ./apps/api
    ports: 
      - "3000:3000"
    container_name: bootcamp-api
  web:
    build: ./apps/web
    ports:
      - "8000:80"
    environment:
      - VITE_API_URL=http://api:3000/api
    depends_on:
      - api
    container_name: bootcamp-web